### PR TITLE
Swam server for wafl

### PR DESCRIPTION
**Pull request by tareq97-zz**

### CODE REVIEW

**Comment by monperrus** [comment]
Great! Could you make the PR against feature/path_coverage so that we see a small diff?

**Comment by Jacarte** [comment]
Since the description is for a feature of the swam server, I moved to a new PR to the swam-server branch #12

**Comment by Jacarte** [comment]
> Great! Could you make the PR against feature/path_coverage so that we see a small diff?

I think is better to have it against the swam-server branch

#12

**Comment by monperrus** [comment]
Ack, we can close this one then.

**Comment by monperrus** [comment]
conflicts there, @Jacarte takes care about them

**Review by Jacarte — APPROVED** [review]

**Comment by monperrus** [comment]
CI is red. Why? Fix or merge?

**Comment by Jacarte** [comment]
> CI is red. Why? Fix or merge?

It is red due to code format checking, this was fixed by Lucas in his repo. It will be fixed once we sync the two master branches

**Comment by Jacarte** [comment]
Now the tests are failing. Fixing...

**Comment by monperrus** [comment]
What about backporting only the code checking changes from Luacs' master there?

**Comment by Jacarte** [comment]
> What about backporting only the code checking changes from Luacs' master there?

My mistake, the rule still exists if it is a PR, I thought it was removed. I think is better for now if we run `./millw __.reformat` before pushing to a PR.

**Comment by monperrus** [comment]
OK, everything is green and approved, we can merge.

**Comment by monperrus** [comment]
Excellent job gentlemen!

**Comment by olapiv** [comment]
Hey, I just saw this. So we're okay with having the socket server in master? Because last thing I knew was that Lucas only wanted the coverage part?

**Comment by monperrus** [comment]
this is only in kth/master, but not in satabin/master

temporarily, as long as we don't have created the standalone project 
with its own build.sbt in slumps.

when this is done, we'll remove from kth/master

**Pull request merged**
